# Generated by Django 3.1.2 on 2021-08-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('task_management', 'Can create, assign and delete tasks')]},
        ),
    ]
